### ISSUE TITLE
`Kube` crashes with `The bridge does not accept secrets`

### ISSUE THREAD

**Issue by Ngoguey42** [ovh/pulumi-ovh#234]
:wave:

I'm following this tutorial and i got this crash during the first `pulumi preview`

https://help.ovhcloud.com/csm/en-gb-public-cloud-kubernetes-create-cluster-with-pulumi?id=kb_article_view&sysparm_article=KB0059714

```
OVH_ENDPOINT="ovh-eu" OVH_APPLICATION_KEY="REDACTED" OVH_APPLICATION_SECRET="REDACTED" OVH_CONSUMER_KEY="REDACTED" pulumi preview



Previewing update (dev):
     Type                      Name               Plan       Info
 +   pulumi:pulumi:Stack       079-dev            create     24 messages
     └─ ovh:CloudProject:Kube  ovh-kube-provider             1 error

Diagnostics:
  pulumi:pulumi:Stack (079-dev):
    panic: fatal: An assertion has failed: The bridge does not accept secrets, so we should not encounter them here
    goroutine 59 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0xc0?, {0x9839290?, 0xc000866660?}, {0x0?, 0xc000102408?, 0xc001290000?})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/go/common/util/contract/assert.go:35 +0xe8
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*ConfigEncoding).UnfoldProperties(0xc001290000, 0xc0005f5ad0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.0/pkg/tfbridge/config_encoding.go:143 +0x2b2
    github.com/pulumi/pulumi-terraform-bridge/pf/internal/configencoding.(*provider[...]).ConfigureWithContext(0xc0004bfc80, {0xa5ed2c8?, 0xc0005f58f0}, 0xc0005f5ad0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.0/internal/configencoding/provider.go:110 +0x45
    github.com/pulumi/pulumi-terraform-bridge/pf/internal/plugin.(*provider).Configure(0xa5826e0?, {0xa5ed2c8?, 0xc0005f58f0?}, {0x0?})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.0/internal/plugin/provider_context.go:143 +0x25
    github.com/pulumi/pulumi-terraform-bridge/pf/internal/plugin.providerThunk.Configure({{0xa616530?, 0xc001293c30?}}, {0xa5ed2c8, 0xc0005f58f0}, {0xffffffffffffffff?})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.0/internal/plugin/provider_server.go:83 +0x76
    github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*providerServer).Configure(0xc001295cb0, {0xa5ed2c8, 0xc0005f58f0}, 0xc000685f00)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/go/common/resource/plugin/provider_server.go:346 +0x331
    github.com/pulumi/pulumi-terraform-bridge/pf/internal/plugin.(*providerServer).Configure(0xa5cd740?, {0xa5ed2c8?, 0xc0005f58f0?}, 0xc00008ffd0?)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.0/internal/plugin/provider_server.go:57 +0x25
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Configure.func1()
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:298 +0x6f
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.asyncJoin[...].func1()
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:595 +0x42
    created by github.com/pulumi/pulumi-terraform-bridge/x/muxer.asyncJoin[...] in goroutine 57
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:594 +0x79

  ovh:CloudProject:Kube (ovh-kube-provider):
    error: error reading from server: EOF
```

```
cat __main__.py Pulumi.dev.yaml Pulumi.yaml requirements.txt



import pulumi_ovh

kube = pulumi_ovh.cloudproject.Kube(
    "ovh-kube-provider",
    service_name="REDACTED",
    name="my-test-cluster",
    region='RBX',
)




encryptionsalt: v1:PVuJFLPLZgw=:v1:zOl9Qzz6398LV0l5:vyZn4SGZlEuEiMVA8zzXP8ib9N6AcA==
name: "079"
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
description: A minimal Python Pulumi program



config:
  pulumi:tags:
    value:
      pulumi:template: python



pulumi>=3.0.0,<4.0.0
pulumi-ovh
```

```
 ls -1a
.
..
.gitignore
Pulumi.dev.yaml
Pulumi.yaml
__main__.py
__pycache__
requirements.txt
venv
```

```
pulumi about



CLI
Version      3.132.0
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  ovh     0.50.0
language  python  unknown

Host
OS       darwin
Version  14.6.1
Arch     x86_64

This project is written in python: executable='/Users/nico/test/079/venv/bin/python' version='3.8.19'

Backend
Name           ngoguey-mbp
URL            file://~
User           nico
Organizations
Token type     personal

Dependencies:
NAME        VERSION
pip         24.2
pulumi_ovh  0.50.0
setuptools  75.1.0
wheel       0.44.0

Pulumi locates its logs in /var/folders/50/ccj8r__12yz02g03vhq93r7c0000gn/T/ by default
warning: Failed to get information about the current stack: No current snapshot
```

**Comment by scraly** [comment]
Hi
yes it appears that pulumi have a blocking bug: https://github.com/pulumi/pulumi-terraform-bridge/issues/2439#issuecomment-2378480281

It should be fixed in the next version
In the meantime, you can use version 0.49 of the ovh pulumi provider

**Comment by Ngoguey42** [comment]
It worked. Thanks @scraly

Feel free to close this issue

**Comment by scraly** [comment]
OVH pulumi provider in 0.50.1 have been released witht he fix of pulumi blocking issue :) 
Please use this new release
